env: GHCVER=7.8.4

before_install:
    - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
    - travis_retry sudo add-apt-repository -y ppa:avsm/ocaml41+opam12
    - travis_retry sudo apt-get update
    - travis_retry sudo apt-get install ghc-$GHCVER ocaml ocaml-native-compilers camlp4-extra
    - export PATH=/opt/ghc/$GHCVER/bin:$PATH
    - ghc --version
    - wget http://www.diku.dk/~paba/coq-8.5beta2-build.tgz
    - tar xf coq-8.5beta2-build.tgz
    - cd coq-8.5beta2
    - sudo make install
    - cd ..
script:
    - cd Coq
    - make
    - cd Extraction
    - make clean
    - make test
